// Centralized Project Data Source of Truth
// Values strictly extracted from E-Commerce_Cleaned.xlsx, E-Commerce RNM(3).ipynb, and AD(1).pbix

export const KPIs = {
  totalRevenue: 9730000,
  totalRevenueFormatted: "9.73M",
  totalOrders: 24000,
  totalOrdersFormatted: "24K",
  uniqueCustomers: 4372,
  uniqueCustomersFormatted: "4K+",
  averageOrderValue: 397.86,
  returnRate: 1.82,
  cancellationRate: 1.73,
  totalQuantity: 5000000,
  totalQuantityFormatted: "5M"
};

export const datasets = {
  raw: {
    rows: "541,909",
    columns: 8,
    fields: ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
  },
  cleaned: {
    rows: "535,187",
    columns: 11,
    newFields: ["Revenue", "IsCancelled", "IsReturn", "Month"]
  }
};

export const monthlyRevenue = [
  { month: "2010-12", revenue: 746723.610 },
  { month: "2011-01", revenue: 558448.560 },
  { month: "2011-02", revenue: 497026.410 },
  { month: "2011-03", revenue: 682013.980 },
  { month: "2011-04", revenue: 492367.841 },
  { month: "2011-05", revenue: 722094.100 },
  { month: "2011-06", revenue: 689977.230 },
  { month: "2011-07", revenue: 680156.951 },
  { month: "2011-08", revenue: 681386.460 },
  { month: "2011-09", revenue: 1017596.682 },
  { month: "2011-10", revenue: 1069368.230 },
  { month: "2011-11", revenue: 1456145.800 },
  { month: "2011-12", revenue: 432701.060 }
];

export const topCountriesByRevenue = [
  { country: "United Kingdom", revenue: 8167128.184 },
  { country: "Netherlands", revenue: 284661.540 },
  { country: "EIRE", revenue: 262993.380 },
  { country: "Germany", revenue: 221509.470 },
  { country: "France", revenue: 197317.110 },
  { country: "Australia", revenue: 137009.770 },
  { country: "Switzerland", revenue: 56363.050 },
  { country: "Spain", revenue: 54756.030 },
  { country: "Belgium", revenue: 40910.960 },
  { country: "Sweden", revenue: 36585.410 }
];

// Top 5 contribution is approximately 93.91%
export const top5CountryContribution = 93.91;

export const topProductsByQuantity = [
  { product: "PAPER CRAFT , LITTLE BIRDIE", quantity: 80995 },
  { product: "MEDIUM CERAMIC TOP STORAGE JAR", quantity: 77800 },
  { product: "WORLD WAR 2 GLIDERS ASSTD DESIGNS", quantity: 54319 },
  { product: "JUMBO BAG RED RETROSPOT", quantity: 46181 },
  { product: "WHITE HANGING HEART T-LIGHT HOLDER", quantity: 36725 },
  { product: "POPCORN HOLDER", quantity: 36118 },
  { product: "PACK OF 72 RETROSPOT CAKE CASES", quantity: 33693 },
  { product: "ASSORTED COLOUR BIRD ORNAMENT", quantity: 35362 },
  { product: "RABBIT NIGHT LIGHT", quantity: 27202 },
  { product: "MINI PAINT SET VINTAGE", quantity: 26076 }
];

// Filtered DOTCOM POSTAGE, POSTAGE, AMAZON FEE, Manual as requested.
export const topProductsByRevenue = [
  { product: "REGENCY CAKESTAND 3 TIER", revenue: 143525.0 },
  { product: "PAPER CRAFT , LITTLE BIRDIE", revenue: 168469.6 },
  { product: "WHITE HANGING HEART T-LIGHT HOLDER", revenue: 100448.15 },
  { product: "PARTY BUNTING", revenue: 98302.98 },
  { product: "JUMBO BAG RED RETROSPOT", revenue: 85220.78 },
  { product: "RABBIT NIGHT LIGHT", revenue: 51137.80 },
  { product: "PAPER CHAIN KIT 50'S CHRISTMAS", revenue: 42560.10 },
  { product: "ASSORTED COLOUR BIRD ORNAMENT", revenue: 56499.22 },
  { product: "CHILLI LIGHTS", revenue: 46286.51 }
];

export const topCustomersByRevenue = [
  { customerId: "14646", revenue: 279489.02 },
  { customerId: "18102", revenue: 256438.49 },
  { customerId: "17450", revenue: 187322.17 },
  { customerId: "14911", revenue: 132458.73 },
  { customerId: "12415", revenue: 123725.45 },
  { customerId: "14156", revenue: 113214.59 },
  { customerId: "17511", revenue: 88125.38 },
  { customerId: "16684", revenue: 65892.08 },
  { customerId: "13694", revenue: 62690.54 },
  { customerId: "15311", revenue: 59284.19 }
];

export const averageRevenuePerCustomer = 1893.53;

export const transactionStatus = [
  { name: 'Completed', value: 96.45, fill: '#3b82f6' }, // Approximate based on remaining %
  { name: 'Returned', value: 1.82, fill: '#f43f5e' },
  { name: 'Cancelled', value: 1.73, fill: '#f59e0b' },
];

// Important business questions grouped into categories
export const businessQuestions = [
  {
    category: "Sales Performance",
    questions: [
      "What is the total revenue generated by the store?",
      "What is the total number of orders?",
      "What is the number of orders per month?",
      "How does revenue change from month to month?",
      "Which month generated the highest revenue?",
      "What is the Average Order Value?",
      "What is the average number of products per order?"
    ]
  },
  {
    category: "Country Analysis",
    questions: [
      "Which countries generate the highest revenue?",
      "Which countries have the highest number of orders?",
      "What is the contribution of the Top 5 Countries to total revenue?",
      "Which countries have the highest Returns/Cancellations rate?"
    ]
  },
  {
    category: "Product Analysis",
    questions: [
      "What are the Top 10 products by quantity sold?",
      "What are the Top 10 products by revenue?",
      "Which products have the highest Average Unit Price?",
      "What is the contribution of the Top 10 Products to total revenue?",
      "Which products are returned or cancelled the most?"
    ]
  },
  {
    category: "Customer Analysis",
    questions: [
      "How many unique customers are in the dataset?",
      "Which customers generate the highest revenue?",
      "What is the average revenue per customer?"
    ]
  },
  {
    category: "Returns & Cancellations",
    questions: [
      "What is the Returns rate from total transactions?",
      "What is the Cancellations rate from total transactions?",
      "How do Returns and Cancellations affect total revenue?"
    ]
  }
];

export const keyInsights = [
  "The United Kingdom generates the majority of total revenue.",
  "The Top 5 countries contribute approximately 93.91% of total revenue.",
  "November 2011 recorded the highest monthly revenue at approximately 1.46M.",
  "A relatively small group of customers generates a significant amount of revenue.",
  "The overall return rate is approximately 1.82%.",
  "The project contains clear differences between product popularity by quantity and product performance by revenue."
];

export const recommendations = [
  "Focus marketing and retention efforts on high-performing markets.",
  "Develop strategies for high-value customers.",
  "Promote high-revenue products.",
  "Monitor products with high return volumes.",
  "Use monthly revenue trends for inventory and sales planning.",
  "Investigate differences between quantity-based and revenue-based product performance."
];
